[package]
version = "1.0.0"
description = "Open Wallet Tracker"
authors = ["Cometix group"]
edition = "2025"

[dependencies]
cometix-sdk = { version = "1.0.16", feature = {"sdk_support"}}
cometix-utils = { version = "1.1.12", features = {"utils", "test-2025"}}
cometix-security = { version = "1.0.52", features = {"sec-wallet"}}
solana-instruction = { version = "2.2.1", features = ["std"] }
solana-pubkey = { version = "2.2.1", features = ["curve25519"] }

[dev-dependencies]
solana-program = "2.2.1"

